# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 3000

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Getting the Rust version is slow
[rust]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
vicmd_symbol = "[Î»](bold green)"
