add_newline = false
command_timeout = 3000

# Getting the Rust version is slow
[rust]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"
vicmd_symbol = "[â†](bold green)"
